[build]
  command = "npm run build"
  publish = "public"  # Ensure this is correct
  functions = "netlify/functions"  # Ensure this is the correct path to your functions



[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
