[build]
  command = "npm install && npm run build"
 

[functions]
  directory = "netlify/functions-build"  # Set this to a directory for built functions


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
